name: crm_win_app
version: 1.0.7+8
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.11.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  http: ^0.13.1
  font_awesome_flutter: ^9.1.0
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  dio: ^4.0.0
  mask_text_input_formatter: ^2.0.0
  brasil_fields: 1.1.3
  change_app_package_name: ^0.1.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

flutter: 
  uses-material-design: true

  assets:
    - images/logo.png
    - images/image.png
    - images/whatsapp.png
    - images/maps.png

